name: Upload Gadle Support Library
on: workflow_dispatch
jobs:
  build:
    name: Build Gadle Support Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running gradle assembleRelease
      run: gradle :gradle-support:assembleDebug

    - name: Uploading Jar Libraries
      uses: actions/upload-artifact@v2
      with:
        name: gradle-support
        path: |
          gradle-support/build/outputs/aar/gradle-support/debug-re-bundle.aar
    
